# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain/domain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64omain/domain.proto\x12\x06\x64omain\"\x1a\n\x05State\x12\x11\n\tlanguages\x18\x01 \x03(\t\"\x1b\n\x07Request\x12\x10\n\x08language\x18\x01 \x01(\t\"\x19\n\x05Reply\x12\x10\n\x08response\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'domain.domain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STATE']._serialized_start=31
  _globals['_STATE']._serialized_end=57
  _globals['_REQUEST']._serialized_start=59
  _globals['_REQUEST']._serialized_end=86
  _globals['_REPLY']._serialized_start=88
  _globals['_REPLY']._serialized_end=113
# @@protoc_insertion_point(module_scope)
