version: "3.8"

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: eigr-functions-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3307:3306"

  nats:
    image: nats:0.8.0
    entrypoint: "/gnatsd -DV"
    ports:
      - "8222:8222"
      - "4222:4222"

  spawn-proxy:
    image: eigr/spawn-proxy:1.0.0-rc.18
    restart: always
    environment:
      PROXY_APP_NAME: spawn
      PROXY_CLUSTER_STRATEGY: gossip
      SPAWN_USE_INTERNAL_NATS: true
      SPAWN_PUBSUB_ADAPTER: nats
      PROXY_DATABASE_PORT: 3307
      PROXY_DATABASE_TYPE: mariadb
      PROXY_HTTP_PORT: 9003
      USER_FUNCTION_PORT: 8091
      SPAWN_STATESTORE_KEY: 3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= iex
    ports:
      - "9003:9003"

networks:
  mysql-compose-network:
    driver: bridge

volumes:
  mariadb:
