# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/protobuf/eigr/functions/spawn/example/messages/messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEexample/protobuf/eigr/functions/spawn/example/messages/messages.proto\x12%eigr.functions.spawn.example.messages\"\x1b\n\x07Request\x12\x10\n\x08language\x18\x01 \x01(\t\"\x19\n\x05Reply\x12\x10\n\x08response\x18\x01 \x01(\tB8\n%eigr.functions.spawn.example.messagesB\rMessagesProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.protobuf.eigr.functions.spawn.example.messages.messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%eigr.functions.spawn.example.messagesB\rMessagesProtoP\001'
  _REQUEST._serialized_start=112
  _REQUEST._serialized_end=139
  _REPLY._serialized_start=141
  _REPLY._serialized_end=166
# @@protoc_insertion_point(module_scope)
