# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eigr/functions/protocol/actors/state.proto
"""Generated protocol buffer code."""
from spawn.eigr.functions.protocol.actors import actor_pb2 as eigr_dot_functions_dot_protocol_dot_actors_dot_actor__pb2
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*eigr/functions/protocol/actors/state.proto\x12\x1d\x65igr.functions.protocol.state\x1a*eigr/functions/protocol/actors/actor.proto\"\x19\n\x08Revision\x12\r\n\x05value\x18\x01 \x01(\x03\"\x82\x01\n\nCheckpoint\x12\x39\n\x08revision\x18\x01 \x01(\x0b\x32\'.eigr.functions.protocol.state.Revision\x12\x39\n\x05state\x18\x02 \x01(\x0b\x32*.eigr.functions.protocol.actors.ActorStateBX\n io.eigr.functions.protocol.stateZ4github.com/eigr/go-support/eigr/protocol/state;stateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'eigr.functions.protocol.actors.state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n io.eigr.functions.protocol.stateZ4github.com/eigr/go-support/eigr/protocol/state;state'
    _globals['_REVISION']._serialized_start = 121
    _globals['_REVISION']._serialized_end = 146
    _globals['_CHECKPOINT']._serialized_start = 149
    _globals['_CHECKPOINT']._serialized_end = 279
# @@protoc_insertion_point(module_scope)
