# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/protobuf/eigr/functions/spawn/example/state/joe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=example/protobuf/eigr/functions/spawn/example/state/joe.proto\x12\"eigr.functions.spawn.example.state\"\x1d\n\x08JoeState\x12\x11\n\tlanguages\x18\x01 \x03(\tB:\n\"eigr.functions.spawn.example.stateB\x12JoeStateStateProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.protobuf.eigr.functions.spawn.example.state.joe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"eigr.functions.spawn.example.stateB\022JoeStateStateProtoP\001'
  _JOESTATE._serialized_start=101
  _JOESTATE._serialized_end=130
# @@protoc_insertion_point(module_scope)
