# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eigr/functions/spawn/example/state/joe.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eigr/functions/spawn/example/state/joe.proto',
  package='eigr.functions.spawn.example.state',
  syntax='proto3',
  serialized_options=b'\n\"eigr.functions.spawn.example.stateB\022JoeStateStateProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,eigr/functions/spawn/example/state/joe.proto\x12\"eigr.functions.spawn.example.state\"\x1d\n\x08JoeState\x12\x11\n\tlanguages\x18\x01 \x03(\tB:\n\"eigr.functions.spawn.example.stateB\x12JoeStateStateProtoP\x01\x62\x06proto3'
)




_JOESTATE = _descriptor.Descriptor(
  name='JoeState',
  full_name='eigr.functions.spawn.example.state.JoeState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='languages', full_name='eigr.functions.spawn.example.state.JoeState.languages', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['JoeState'] = _JOESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoeState = _reflection.GeneratedProtocolMessageType('JoeState', (_message.Message,), {
  'DESCRIPTOR' : _JOESTATE,
  '__module__' : 'eigr.functions.spawn.example.state.joe_pb2'
  # @@protoc_insertion_point(class_scope:eigr.functions.spawn.example.state.JoeState)
  })
_sym_db.RegisterMessage(JoeState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
